// Fill out your copyright notice in the Description page of Project Settings.


#include "AI/Monster/MonsterTag.h"

namespace TSMoonsterTag
{
	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_CHASER, "Monster.Chaser");
	
	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_SENTINEL, "Monster.Sentinel");
	
	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_WANDERER, "Monster.Wanderer");
	
	
	///

	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_TRY_ATTACK, "Monster.Behavior.TryAttack");
	
	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_RECEIVE_HIT, "Monster.Behavior.ReceiveHit");

	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_RECEVIE_TARGET, "Monster.Behavior.ReceiveTarget");

	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_FORGET_TARGET, "Monster.Behavior.ForgetTarget");

	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_NEED_TO_FIND_TARGET, "Monster.Behavior.NeedToFindTarget");
	
	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_ENDATTACK_MONATAGE, "Monster.Behavior.EndAttackMontage");
	
	TINYSURVIVOR_API UE_DEFINE_GAMEPLAY_TAG(TP_MONSTER_MONSTER_DIE, "Monster.Behavior.MonsterDie");

}

