// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace TSMoonsterTag
{
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_CHASER);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_SENTINEL);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_WANDERER);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_WANDERER_FORHORDE);
	
	///
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_TRY_ATTACK);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_RECEIVE_HIT_NOTIFY);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_RECEIVE_HIT);

	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_RECEVIE_TARGET);

	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_FORGET_TARGET);

	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_CHECKING_TARGET);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_NEED_TO_FIND_TARGET);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_LOST_TARGET);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_ENDATTACK_MONATAGE);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_MONSTER_DIE);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_TRY_PRAY);
	
	TINYSURVIVOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TP_MONSTER_TRY_SHOOT_PROJCETILE);
	
}

